#!/bin/sh

# Set these paths appropriately

BIN="/home/luxinyao/Documents/LegalNER_GdCL_III_Projekt/LegalNER/TreeTagger/bin"
CMD="/home/luxinyao/Documents/LegalNER_GdCL_III_Projekt/LegalNER/TreeTagger/cmd"
LIB="/home/luxinyao/Documents/LegalNER_GdCL_III_Projekt/LegalNER/TreeTagger/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
